name: CI

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request:
    branches:
      - main # Run for PRs targeting the main branch

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Update to match your project requirements

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt  # Update path if needed

      - name: Run Backend Tests
        run: |
          cd server
          pytest  # Add options like `--cov` for coverage if needed

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Update to match your project requirements

      - name: Install Dependencies
        run: |
          cd client
          npm ci  # Use npm ci for clean installs

      - name: Run Frontend Tests
        run: |
          cd client
          npm test  # Ensure this is configured in your package.json

  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Linter Dependencies
        run: |
          python -m pip install flake8
          pip install -r server/requirements.txt  # Update path if needed

      - name: Lint Backend Code
        run: |
          flake8 server  # Ensure flake8 is installed and configured in your project

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Lint Frontend Code
        run: |
          cd client
          npm run lint  # Ensure linting scripts are set up in your package.json
